### ISSUE TITLE
データベース作成

### ISSUE THREAD

**Issue by daaaisuke** [sho-chan/select#11]
## データベースのテーブルとカラムの詳細
- admin
  - id:int
  - password:
- about
  - introduce:string
  - men:int
  - women:int
  - price:int
- schedule
  - about_id
  - January:string
  - February:string
  - March:string
  - April:string
  - May:string
  - Jun:string
  - July:string
  - August:string
  - September:string
  - October:string
  - November:string
  - December:string
- university
  - about_id
  - name:string
- place
  - about_id
  - name:string
  - address:string
  - url:string
  - image-url:string

**Comment by shiiiiiiiii1** [comment]
**adminの管理者画面ページは誰が見てもわかるように、詳細のやり方なども書いておかなければならない。**
